name: CI

on:
  push:
    branches: [ main ] 

jobs:
  test-lint:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: '1.11'

      - name: Install dependencies
        run: |
          julia --project=. -e 'using Pkg; Pkg.instantiate()'

      - name: Lint code (optional)
        run: |
          julia --project=. -e '
            using Pkg;
            Pkg.add("JuliaFormatter");
            using JuliaFormatter;
            format(".", verbose=true, check=true);
          '

      - name: Run tests
        run: |
          julia --project=. -e 'using Pkg; Pkg.test()'
